### ISSUE TITLE
MMGBSA

### ISSUE THREAD

**Issue by kmb413** [kmb413/DecoyDiscrimination#10]
Hi Hai,

I was trying to use the MMPBSA python parser, and am getting an error. I can successfully import the module 

`from MMPBSA_mods import API as MMPBSA_API
`

But when I use:

`>>> data = MMPBSA_API.load_mmpbsa_info('_MMPBSA_info')
`

I get:

> Traceback (most recent call last):  
>   File "<stdin>", line 1, in <module>  
>   File "/scratch/kmb413/amber_jan142016/lib/python2.7/site-packages/MMPBSA_mods/API.py", line 358, in load_mmpbsa_info  
>     app.parse_output_files()  
>   File "/scratch/kmb413/amber_jan142016/lib/python2.7/site-packages/MMPBSA_mods/main.py", line 930, in parse_output_files  
>     self.using_chamber)}  
> AttributeError: 'MMPBSA_App' object has no attribute 'using_chamber'

I have so far tried to rebuild the /src directory in AmberTools and get the same issue. Any ideas?

Thanks!

Kristin

**Comment by hainm** [comment]
can you try to follow this?

http://archive.ambermd.org/201505/0438.html

**Comment by kmb413** [comment]
Thanks! Also found the part in the mmgbsa.in where you specify the number of residues to print, so thanks for that too.
