### ISSUE TITLE
Can I Join Your Group?

### ISSUE THREAD

**Issue by kmb413** [kmb413/DecoyDiscrimination#4]
Hi @hainm,

So Gyges is being decommissioned and Bill said we should be moving our stuff off of that server. It was so difficult to set up the proper environment for pytraj and amber before, so do you think I could join one of your casegroup servers or another server where all of this is working so we don't have to go through the headache again? I tried to move all of my gyges info to the tyr server before but I ran out of room, so I don't think we can work there.

**Comment by hainm** [comment]
@kmb413 for this issue, can you discuss with your advisor and ask prof. Case?

are you going to have account in new cluster (I just got news from Koji Tanaka for ELF1)?

you encountered the install issue before because you only has official Amber14 while pytraj was introduced in Amber15. But I can send you the development version of amber16 (which has cpptraj, pytraj, pysander, parmed, ...) and the install is much easier. Or I can just install them for you.

Keep me update about account stuff. thanks.

**Comment by hainm** [comment]
http://rdi2.rutgers.edu/elf-i

**Comment by kmb413** [comment]
Oh, I didn't know it was b/c of Amber14. Can you help me install Amber16 locally on the fen server? Fen has its own Amber though, do you think these would conflict? Thanks!!

**Comment by hainm** [comment]
>  Can you help me install Amber16 locally on the fen server

I am  not sure if I have access to fen server. can you send me (via gmail the address so I can try?)

> ? Fen has its own Amber though, do you think these would conflict

Which version? amber14?
does it install libsander? can you try `python -c 'import sander'`? 

we can meet tomorrow afternoon to chat about the installation.

**Comment by kmb413** [comment]
So the 'make install' finished, and I did 'source amber.sh' but still can't import pytraj.

'which python' gives: 
/scratch/kmb413/miniconda3/bin/python

'echo $AMBERHOME' gives:
/scratch/kmb413/amber_jan142016

'echo $PATH’:
/scratch/kmb413/miniconda3/bin:/scratch/kmb413/amber_jan142016/bin:/scratch/kmb413/amber_jan142016/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/home/kmb413/local:/home/kmb413/local/bin:/sbin:/home/kmb413:/apps/amber/amber14/bin:/home/kmb413/local:/home/kmb413/local/bin:/sbin:/home/kmb413

'echo $LD_LIBRARY_PATH' gives:
/scratch/kmb413/amber_jan142016/lib:/scratch/kmb413/amber_jan142016/lib:/home/kmb413/PyRosetta.ScientificLinux-r56324.64Bit/rosetta:/home/svensken/local/lib

In python, I get:

Python 3.5.1 |Continuum Analytics, Inc.| (default, Dec  7 2015, 11:16:01)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.

> - import sys
> - print(sys.path)
>   ['', '/scratch/kmb413/amber_jan142016/lib/python2.7/site-packages', '/home/kmb413/PyRosetta.ScientificLinux-r56324.64Bit', '/lustre/cs1500/scratch/kmb413', '/scratch/kmb413/miniconda3/lib/python35.zip', '/scratch/kmb413/miniconda3/lib/python3.5', '/scratch/kmb413/miniconda3/lib/python3.5/plat-linux', '/scratch/kmb413/miniconda3/lib/python3.5/lib-dynload', '/scratch/kmb413/miniconda3/lib/python3.5/site-packages', '/scratch/kmb413/miniconda3/lib/python3.5/site-packages/setuptools-19.2-py3.5.egg']
> - import pytraj as pt
>   Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   ImportError: No module named 'pytraj'

If I do 'source activate test', I can import pytraj fine. I cannot import sander.

source activate test
discarding /scratch/kmb413/miniconda3/bin from PATH
prepending /scratch/kmb413/miniconda3/envs/test/bin to PATH

(test)kmb413 fen kmb413 $ echo $AMBERHOME
/scratch/kmb413/amber_jan142016

(test)kmb413 fen kmb413 $ echo $PATH
/scratch/kmb413/miniconda3/envs/test/bin:/scratch/kmb413/amber_jan142016/bin:/scratch/kmb413/amber_jan142016/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/home/kmb413/local:/home/kmb413/local/bin:/sbin:/home/kmb413:/apps/amber/amber14/bin:/home/kmb413/local:/home/kmb413/local/bin:/sbin:/home/kmb413

(test)kmb413 fen kmb413 $ echo $LD_LIBRARY_PATH
/scratch/kmb413/amber_jan142016/lib:/scratch/kmb413/amber_jan142016/lib:/home/kmb413/PyRosetta.ScientificLinux-r56324.64Bit/rosetta:/home/svensken/local/lib
(test)kmb413 fen kmb413 $ which python
/scratch/kmb413/miniconda3/envs/test/bin/python

Python 3.5.1 |Continuum Analytics, Inc.| (default, Dec  7 2015, 11:16:01)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.

> - import sys
> - print(sys.path)
>   ['', '/scratch/kmb413/amber_jan142016/lib/python2.7/site-packages', '/home/kmb413/PyRosetta.ScientificLinux-r56324.64Bit', '/lustre/cs1500/scratch/kmb413', '/scratch/kmb413/miniconda3/envs/test/lib/python35.zip', '/scratch/kmb413/miniconda3/envs/test/lib/python3.5', '/scratch/kmb413/miniconda3/envs/test/lib/python3.5/plat-linux', '/scratch/kmb413/miniconda3/envs/test/lib/python3.5/lib-dynload', '/scratch/kmb413/miniconda3/envs/test/lib/python3.5/site-packages', '/scratch/kmb413/miniconda3/envs/test/lib/python3.5/site-packages/setuptools-19.2-py3.5.egg']
> - import pytraj as pt
> - import sander
>   Traceback (most recent call last):
>   File "/scratch/kmb413/amber_jan142016/lib/python2.7/site-packages/sander/**init**.py", line 13, in <module>
>     from . import pysander as _pys
>   ImportError: /scratch/kmb413/amber_jan142016/lib/python2.7/site-packages/sander/pysander.so: undefined symbol: _Py_ZeroStruct
> 
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/scratch/kmb413/amber_jan142016/lib/python2.7/site-packages/sander/**init**.py", line 15, in <module>
>     raise ImportError('Could not import the compiled Python-sander interface. '
> ImportError: Could not import the compiled Python-sander interface. Make sure you add $AMBERHOME/lib to LD_LIBRARY_PATH or Make sure you have the Python development libraries installed and try rebuilding the serial installation of AMBER.

Everything seems to be about the same as far as the paths go, except for the /envs/test/ part for the test environment. Do you have any ideas why it can't find pytraj in the deactivated environment?

**Comment by hainm** [comment]
my bad :D 
- first, do not activate 'test' environment. I just wanted to show how good conda is. You should `source deactivate` to return original env

> /scratch/kmb413/amber_jan142016/lib/python2.7/site-packages/sander/pysander.so: undefined symbol: _Py_ZeroStruct
- here is the problem:
  we were installing amber while installing miniconda for python3.5. We did `./configure gnu` **before** having python3.5, so amber just looked for default python env (python 2.7). So after making install, everything go to `/scratch/kmb413/amber_jan142016/lib/python2.7/` folder.

# solution
- (optional) delete /scratch/kmb413/amber_jan142016/lib/python2.7
- redo installing amber (will be quick since you already installed most of programs)
  - ./configure gnu # to update path to newly installed python3.5
  - make install -j8 # to speed up
  - source amber.sh
- try again: `python -c 'import pytraj; import sander'`

(To make sure, you can open $AMBERHOME/config.h, you should see python 3.5 dir)

Let me know if this works.

**Comment by hainm** [comment]
> If I do 'source activate test', I can import pytraj fine. I cannot import sander.

because in `test` env, I did `conda install -c ambermd pytraj`, which would install `pytraj` from https://anaconda.org/ambermd/pytraj-dev. So this `pytraj` does not come from AMBER.

You need to install amber suite to have sander and pysander.

**Comment by kmb413** [comment]
Yeah, that didn't work either. I redid ./configure gnu, make install and it couldn't find pytraj module. Then I deleted python2.7, redid ./configure gnu, make install and some problem.

**Comment by hainm** [comment]
uhm, this is weird. Did you `source amber.sh` after `./configure gnu` and `make install`?

**Comment by kmb413** [comment]
Yeah, Did that too.

**Comment by hainm** [comment]
uhm, I am kind of worry that installing pysander and pytraj will cause issue for other users too. So I am just trying to debug here.
- First, do you see `pytraj` in 
  `'/scratch/kmb413/amber_jan142016/lib/python3.5/site-packages/` folder?

if `yes`, can you just go to that folder `/scratch/kmb413/amber_jan142016/lib/python3.5/site-packages/`
and `python -c  'import pytraj'`?
- second, can you import sander? `python -c 'import sander'? have you seen`sander`in 
  `/scratch/kmb413/amber_jan142016/lib/python3.5/site-packages/`?

**Comment by kmb413** [comment]
Sure! Looks like pytraj is not in the folder, but sander is. I can import sander in python just fine.

**Comment by hainm** [comment]
can you 
- `cd $AMBERHOME/AmberTools/src`
- `make pytraj -j8`

What happens then? (can you paste the log here?).

**Comment by kmb413** [comment]
Building from source requires cython >= 0.21

Either try:
    conda install cython
    pip install cython --upgrade

I'll install cython with conda.

**Comment by hainm** [comment]
ack, so this is the error

just
`conda install cython`

oh, but you can just install pre-compiled pytraj from ambermd channel
`conda install -c ambermd pytraj-dev`. (we did this with `test` env).

**Comment by kmb413** [comment]
OMG. It works.

**Comment by hainm** [comment]
OMG, great. :D

**Comment by hainm** [comment]
@kmb413 so is this issue can be closed now?
